trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: AngularTools
    type: git
    name: 'BSR-AlphaBetaImplementation/AngularTools'
    ref: refs/heads/main

extends:
  template: /pipelines/swa_template.yml@AngularTools  # Replace with the actual path
  parameters:
    projectName: 'MOR'
