trigger:
  - classic-build

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: AngularTools
    type: git
    name: 'BSR-AlphaBetaImplementation/AngularTools'

stages:
- stage: BuildTools
  jobs:
  - job: InstallNet7
    steps:
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 7.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
  - job: Checkout
    steps:
    - checkout: Self
    - checkout: AngularTools
      path : s/AngularTools
    - script: ls /home/vsts/work/1
    - script: ls /home/vsts/work/1/s
      displayName: 'List Root Directory'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/AddGoogleTagManager.sln'  # Adjust path as needed
      displayName: 'Restore AngularTools Dependencies'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/AddGoogleTagManager.csproj'  # Adjust path as needed
        arguments: '--configuration $(BuildConfiguration) --runtime linux-x64 --output $(Build.SourcesDirectory)/HSE.MOR.Client/HseTools'
      displayName: 'Build AngularTools Project'
    - task: NodeTool@0
      inputs:
        versionSpec: '18.16.x'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: 'HSE.MOR.Client'
    - task: Npm@1
      inputs:
        command: 'run'
        workingDir: 'HSE.MOR.Client'
        arguments: 'build'
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'HSE.MOR.Client/dist'
        Contents: '**'
        TargetFolder: 'HSE.MOR.Client'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true
        preserveTimestamp: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/HSE.MOR.Client'
        ArtifactName: HSE.MOR.Client

- stage: UnitTest
  jobs:
  - job: 
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Run Unit Tests'
        inputs:
          command: 'test'
          projects: '**/HSE.MOR.API.UnitTests.csproj'
      - task: DotNetCoreCLI@2
        displayName: 'Build API'
        inputs:
          command: 'build'
          projects: 'HSE.MOR.API/HSE.MOR.API.csproj'
          arguments: '--output publish_output --configuration Release'
      - task: ArchiveFiles@2
        displayName: 'Archive API files'
        inputs:
          rootFolderOrFile: 'publish_output/'
          includeRootFolder: false 
          archiveFile: '$(Build.ArtifactStagingDirectory)/HSE.MOR.API.zip'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish API artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/HSE.MOR.API.zip'
          ArtifactName: HSE.MOR.API
      
