trigger:
- template-build

resources:
  repositories:
  - repository: AzureTools
    type: git
    name: 'BSR-AlphaBetaImplementation/AzureTools'
    ref: refs/heads/main

extends:
  template: 'pipelines/swa_template.yml@AzureTools'  # Replace with the actual path
  parameters:
    projectName: 'MOR'
